### ISSUE TITLE
generateNotes error after merging pull request

### ISSUE THREAD

**Issue by olegshilov** [qiwi/multi-semantic-release#54]
God day.
Today I faced a  problem, which is very similar to dhoulb/multi-semantic-release#64.
Is it possible to get a fix from here dhoulb/multi-semantic-release#65 into this fork?

I'm use `@qiwi/multi-semantic-release` v3.15.0

```log
[2:02:27 PM] [yarn-workspace-release-pack-2] › ✖  Failed step "generateNotes" of plugin "Inline plugin"
[2:02:27 PM] [yarn-workspace-release-pack-2] › ✖  An error occurred while running semantic-release: TypeError: Cannot read property 'filter' of undefined
    at generateNotes (/Users/olegshilov/Documents/yarn-workspace-release/.yarn/unplugged/@semantic-release-release-notes-generator-virtual-dcd04af038/node_modules/@semantic-release/release-notes-generator/index.js:48:8)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async validator (/Users/olegshilov/Documents/yarn-workspace-release/.yarn/cache/semantic-release-npm-17.4.4-8924e8d598-870b4df485.zip/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /Users/olegshilov/Documents/yarn-workspace-release/.yarn/cache/semantic-release-npm-17.4.4-8924e8d598-870b4df485.zip/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /Users/olegshilov/Documents/yarn-workspace-release/.yarn/cache/semantic-release-npm-17.4.4-8924e8d598-870b4df485.zip/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as generateNotes] (/Users/olegshilov/Documents/yarn-workspace-release/.yarn/cache/semantic-release-npm-17.4.4-8924e8d598-870b4df485.zip/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async generateNotes (/Users/olegshilov/Documents/yarn-workspace-release/.yarn/cache/@qiwi-multi-semantic-release-npm-3.15.0-78677a7411-a908a343bb.zip/node_modules/@qiwi/multi-semantic-release/lib/createInlinePluginCreator.js:166:17)
    at async validator (/Users/olegshilov/Documents/yarn-workspace-release/.yarn/cache/semantic-release-npm-17.4.4-8924e8d598-870b4df485.zip/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /Users/olegshilov/Documents/yarn-workspace-release/.yarn/cache/semantic-release-npm-17.4.4-8924e8d598-870b4df485.zip/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /Users/olegshilov/Documents/yarn-workspace-release/.yarn/cache/semantic-release-npm-17.4.4-8924e8d598-870b4df485.zip/node_modules/semantic-release/lib/plugins/pipeline.js:31:3 {
  pluginName: 'Inline plugin'
}
```

**Comment by antongolub** [comment]
Hey, @olegshilov,

We'll land this fix asap.

**Comment by olegshilov** [comment]
@antongolub great! thanks!!
